[tox]
envlist = py310-gpu, py312, lint, complexity
skip_missing_interpreters = true
isolated_build = true
# Default environment configuration for testing
[testenv]
deps =
    pytest
    flake8
    black
    pylint
    radon
commands =
    pytest
    flake8 bgraph/
    black --check bgraph/
    pylint bgraph/
    radon cc bgraph/ -a                             #McCabe Complexity
    radon mi bgraph/                                #Maintainability index MI(171−5.2lnV−0.23G−16.2lnL)
    radon raw bgraph/                               # Raw metrics (LOC, LLOC, SLOC)
    radon hal bgraph/                               # Metrics based on operators and operands

# python environment for running GPU-based community detection

[testenv:py310-gpu]   
basepython = python3.10
set-env =
 USE_CUGRAPH = 1
 NETWORKX_BACKEND_PRIORITY = cugraph
pip_pre =
 --extra-index-url https://pypi.nvidia.com
deps =
 networkx>=3.2
 nx-cugraph-cu12
 matplotlib
commands =
   python scripts-gpu/{posargs}

   
# Python 3.12 environment
[testenv:py312]
basepython = python3.12
deps =
    pytest
commands =
    pytest

# Linting environment: Includes Flake8 and Black
[testenv: lint]
skip_install=true
description = run linters (flake8, black, pylint)
deps =
    flake8
    black
    pylint
commands =
    flake8 bgraph/
    black --check bgraph/
    pylint bgraph/

# Cyclomatic complexity checks using Radon
[testenv: complexity]
skip_install=true
description = check cyclomatic complexity using radon
deps =
    radon
commands =
    radon cc bgraph/ -a                             #McCabe Complexity
    radon mi bgraph/                                #Maintainability index MI(171−5.2lnV−0.23G−16.2lnL)
    radon raw bgraph/                               # Raw metrics (LOC, LLOC, SLOC)
    radon hal bgraph/                               # Metrics based on operators and operands
    
# Custom configurations for Pylint
[testenv:pylint]
description = run pylint with custom configuration
deps =
    pylint
commands =
    pylint bgraph/


